name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2    
    
    - name: Deploy to Production
      uses: SamKirkland/FTP-Deploy-Action@4.3.0
      with:
        server: ${{ secrets.FTP_URLSERVER }}
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        local-dir: ./ # Cambia esto si necesitas subir solo una carpeta específica.
        server-dir: / # Cambia esto si necesitas subir a una carpeta específica.
        dry-run: false # Asegúrate de que no esté en modo de prueba.
        dangerous-clean-slate: false # Solo sube los archivos modificados.
        exclude: |
          .git*
          node_modules/
          vendor/
          .env
